// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestionale_Personale_mvc.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20240930051157_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Dipendente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataDiNascita")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MansioneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatisticheId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MansioneId");

                    b.HasIndex("StatisticheId");

                    b.ToTable("Dipendenti");
                });

            modelBuilder.Entity("Mansione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Stipendio")
                        .HasColumnType("REAL");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mansioni");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Stipendio = 20000.0,
                            Titolo = "Impiegato"
                        },
                        new
                        {
                            Id = 2,
                            Stipendio = 25000.0,
                            Titolo = "Programmatore"
                        },
                        new
                        {
                            Id = 3,
                            Stipendio = 70000.0,
                            Titolo = "Dirigente"
                        });
                });

            modelBuilder.Entity("Statistiche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Fatturato")
                        .HasColumnType("REAL");

                    b.Property<int>("Presenze")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Statistiche");
                });

            modelBuilder.Entity("Dipendente", b =>
                {
                    b.HasOne("Mansione", "Mansione")
                        .WithMany()
                        .HasForeignKey("MansioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Statistiche", "Statistiche")
                        .WithMany()
                        .HasForeignKey("StatisticheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mansione");

                    b.Navigation("Statistiche");
                });
#pragma warning restore 612, 618
        }
    }
}
